---
services:
  odoo_name:
    image: myodoo17:1.0
    # user: root
    ports:
      - "10015:8069"
      - "20015:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=hostdb
      - USER=odoo
      - PASSWORD=odoo17ss
    volumes:
      #- /etc/timezone:/etc/timezone:trt
      #- /etc/localtime:/etc/localtime:trt
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - /opt/AdwatModules:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      odoo_name:
      odoo-network:
        # ipv4_address: 172.25.0.3  # Static IP for odoo17
networks:
  odoo_name:
    driver: bridge  # Internal network
  odoo-network:
    external: true
