version: '3.4'
services:
  db:
    image: postgres:14.13
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17ss
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      odoo_name:
      # odoo-network:
      #   ipv4_address: 172.25.0.2  # Static IP for PostgreSQL
  odoo_name:
    image: odoo:17.0
    # user: root
    depends_on:
      - db
    ports:
      - "10015:8069"
      - "20015:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17ss
    volumes:
      #- /etc/timezone:/etc/timezone:trt
      #- /etc/localtime:/etc/localtime:trt
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - /opt/AdwatModules:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      odoo_name:
      odoo-network:
        ipv4_address: 172.25.0.3  # Static IP for odoo17

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: shared-pgadmin-db
  #   ports:
  #     - 5053:5050
  #   restart: always
  #   links:
  #     - db:db
  #   environment:
  #     DEFAULT_USER: admin
  #     DEFAULT_PASSWORD: YbrS9eP4!j
  #   # VIRTUAL_HOST: 
  #   # LETSENCRYPT_HOST:
  #   # VIRTUAL_PORT: 5050
  #   volumes:
  #     - ./pgadmin-data:/var/lib/pgadmin
  #     #- /var/run/docker.sock:/tmp/docker.sock
  #   networks:
  #     odoo-network:
  #       ipv4_address: 172.25.0.12  # Static IP for odoo17
networks:
  odoo_name:
    driver: bridge  # Internal network
  odoo-network:
    external: true
    # ipam:
    #   config:
    #     - subnet: 172.25.0.0/16  # This allows for 1022 usable IP addresses
